# Generated by Django 5.1.5 on 2025-03-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFit', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
