# Generated by Django 5.2.3 on 2025-06-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFit', '0007_membershipplan_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='features',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='features',
            field=models.ManyToManyField(blank=True, to='coreFit.membershipfeature'),
        ),
    ]
