# Generated by Django 5.2.3 on 2025-06-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFit', '0008_membershipfeature_remove_membershipplan_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
